### ISSUE TITLE
Blob link gets broken

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/github-autolink#4]
## Bug Report

**Current Behavior**
When pasting a link to a blob/src URL, this extension breaks the text into a link to the repository homepage and some un-clickable text for the remaining of the URL.

**Steps to Reproduce**
Post link like https://github.com/s9e/TextFormatter/blob/ee19656423606c5b0595f9d48db62ee0ad31ff08/src/Plugins/BBCodes/Configurator/repository.xml#L46-L74

**Expected Behavior**
If the URL is unsupported, at least the link should remain untouched.

**Screenshots**
![image](https://github.com/FriendsOfFlarum/github-autolink/assets/5264300/df7576b7-634a-4512-bde6-63286531fb92)
Screenshot of this post https://discuss.flarum.org/d/33522-how-to-serve-hljs-loader-at-1033loaderminjs-on-local-server/2

**Environment**
Observed on Flarum Discuss, which seems to be running 1.1.2

**Comment by NathanSweet** [comment]
I am also having this problem. Example:
https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-sdl#spine-version
Becomes:
![](http://n4te.com/x/8631-rqiV.png)

**Comment by imorland** [comment]
Also: https://discuss.flarum.org/d/33610-duplicate-emails/2

![image](https://github.com/FriendsOfFlarum/github-autolink/assets/16573496/a75a5eb8-6ce0-438d-bd72-574ed6d65691)

**Comment by NathanSweet** [comment]
Since the extension currently wrecks most GitHub links, I have had to disable it. Unfortunately when doing so all the GitHub links revert to unclickable text. I look forward to the fix for this issue!
